#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
      cd "$(dirname "${FILE_SOURCE}")" && pwd
    )
  fi
}

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(script_dir)"

  local DESTINATION_FOLDER="${SCRIPT_DIR}/ffmpeg"

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    curl --disable --silent --show-error --location --max-time 600 --output "ffmpeg.zip" "https://evermeet.cx/ffmpeg/get/zip"
    unzip "ffmpeg.zip" -d "${DESTINATION_FOLDER}"
    rm -f "ffmpeg.zip"

    curl --disable --silent --show-error --location --max-time 600 --output "ffprobe.zip" "https://evermeet.cx/ffmpeg/get/ffprobe/zip"
    unzip "ffprobe.zip" -d "${DESTINATION_FOLDER}"
    rm -f "ffprobe.zip"
  else
    for arch in 64 arm64; do
      local ARCHIVE_NAME="ffmpeg-master-latest-linux${arch}-gpl.tar.xz"

      local DESTINATION_ARCH="${arch}"
      if [[ ${DESTINATION_ARCH} == "64" ]]; then
        DESTINATION_ARCH="amd64"
      fi

      local TARGET_NAME="${DESTINATION_FOLDER}/linux/${DESTINATION_ARCH}"

      if [[ -e "${TARGET_NAME}/ffmpeg" ]]; then
        printf "File already present for linux/%s, skipping download." "${arch}"
        continue
      fi

      printf "Downloading static ffmpeg for linux/%s\n" "${arch}"

      curl --disable --silent --show-error --location --max-time 600 --remote-name "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/${ARCHIVE_NAME}"
      mkdir -p "${TARGET_NAME}"
      tar -xf "${ARCHIVE_NAME}" -C "${TARGET_NAME}" --strip 1
      rm -rf "${ARCHIVE_NAME}"
    done
  fi
}

main "${@}"
