apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vignet
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: vignet
    image:
      name: rg.fr-par.scw.cloud/vibioh/vignet
      tag: "202504140814" # {"$imagepolicy": "default:flux-vignet-api:tag"}
    labels:
      tags.datadoghq.com/env: "production"
      tags.datadoghq.com/service: "vignet"
      tags.datadoghq.com/version: "202504140814" # {"$imagepolicy": "default:flux-vignet-api:tag"}
    env:
      - name: GOMAXPROCS
        valueFrom:
          resourceFieldRef:
            resource: limits.cpu
      - name: GOMEMLIMIT
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
      - name: VERSION
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/version']
      - name: OTEL_SERVICE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tags.datadoghq.com/service']
    strategy:
      type: Recreate
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vignet
    volumeMounts:
      - name: data
        mountPath: /data
    config:
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/vignet
      VIGNET_LOGGER_JSON: "true"
      VIGNET_PPROF_AGENT: http://datadog.observability:8126
      VIGNET_STORAGE_FILE_SYSTEM_DIRECTORY: "/data"
      VIGNET_TELEMETRY_URL: datadog.observability:4317
    secrets:
      VIGNET_AMQP_URI: AgC07xkYPOX21xjC7ghwOd49USmrpYO+/8UwGUI9epuz4CamfQZO0fGI9CymzAWMgE5Z+j5xZiSXegIGdAEHqz0/RSdq65HvhrF814dNvb0r74sHCTkEDwn0u4Gkijtl1BJHzy5HNmEhJCR1TDYlGjT+Y8nsGHzg4cN+q9NUJUbiFMvuxGhNA/ghp025OGgNfdjK0/lQpGVg0ZSP+eR/2mhL8EuEvbO4izfu8nlQ8b2R49ytMZrEUtJoJFluq/2jWVxJR6EcsNyNaZ2i0PHovoOfLE9ndIuHV89zxXaNR3CRZ+t6FWCdON6eiS+Pqch4fxqt6MoIBXqhMo6hG+cdMZ9Y/t9YHboK+3C07Q+otHf00ME8+Fv5/2ERnoUdMKFfkalCDjhDrV5c1UegPv1qNkZPoOWupap7ktnbS6w+ZJ4tVKyPgD9DAbo8uawmfFdnEq75Z62MQfkL4vlTlw7HCzwiCNQSo1DHczaFUrKrULXrUib/L/n05t6BGiCZtkj6bymRuX+D/bC2VsRjh2f0zaAJCilH3SMqeNb/7Fx12mcez1G1UHC3VkAmVbI3jBSCykwRLZZWcatDylYuTXuuA9nfjk+J3lXfzGio5KUo0Jiwq8icEBL+O3VfpoW6HWcDUOVFTFKsE+U5KC2gmMbNmWl/CIi67HesbFbbZvFdxIScKJ1SezEHMhh/HWorwSA20j1RLaRkVF/W/WPDs6dymVobylbLymxjRx+Sq2iFw/yWaeAMfPrQirdN73qBRPZ1lRzg
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "256Mi"
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    autoscaling:
      enabled: false
